version: "3.9"

services:
    database:
        image: mysql:5.7
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: smarthealth
